apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
        app: myapp

spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - name: myapp-port
		  containerPort: 8090
		volumeMounts:
        - name: myapp-volume
          mountPath: /var/www
