apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1
	volumeMounts:
    - name: myapp-volume
      mountPath: /var/www
  volumes:
  - name: myapp-volume
    hostPath:
	  path: /var/www
	  type: Directory
